---
- name: install yum repo
  template:
    owner=root
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo

- name: Install docker
  yum: name={{ item }} state=latest
  with_items:
    - docker-engine
    - python-docker-py
