---
- hosts: all
  become: yes
  become_user: root
  roles:
    - roles/common

- hosts: bootstrap, master
  become: yes
  become_user: root
  roles:
    - roles/abaez.docker

- hosts: bootstrap
  become: yes
  become_user: root
  roles:
    - roles/bootstrap

- hosts: master
  become: yes
  become_user: root
  vars:
    - server_role: "master"
  roles:
    - roles/dcos-node

- hosts: agent
  become: yes
  become_user: root
  vars:
    - server_role: "agent"
  roles:
    - roles/dcos-node
