---
- hosts: all
  become: yes
  become_user: root
  roles:
    - roles/common

- hosts: bootstrap, master
  become: yes
  become_user: root
  roles:
    - roles/abaez.docker

- hosts: bootstrap
  become: yes
  become_user: root
  roles:
    - roles/bootstrap
