---
- name: ensure ELRepo repository key is present
  rpm_key: state=present key=https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: ensure ELRepo package is present
  yum: name=http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm state=present

- name: ensure installed packages are up to date
  yum: name=* state=latest update_cache=yes

- name: ensure kernel-ml package is present
  yum: name=kernel-ml state=present enablerepo=elrepo-kernel
